In [1]:
# pip install numpy
import numpy as np

''' numpy란 \
    numeric python의 약자\
    n차원 배열 (ndarray)을 이용한 행렬 연산(성분별 연산)을 통해 고속 연산을 제공하는 라이브러리
    ndarray는 동일 타입의 원소를 담고, shape과 dtype이라는 속성을 가진다.'''


' numpy란     numeric python의 약자    n차원 배열 (ndarray)을 이용한 행렬 연산(성분별 연산)을 통해 고속 연산을 제공하는 라이브러리\n    ndarray는 동일 타입의 원소를 담고, shape과 dtype이라는 속성을 가진다.'

In [2]:
# array함수를 통해 ndarray 생성 (인자로 sequence 전달)
arr = np.array([1,2,3])
# ndarray의 속성값
print(arr.ndim,arr.dtype,arr.shape)
# astype함수를 통해 type을 변경한 ndarray를 생성할 수 있다. => 이를 통해 정수로 이루어진 문자열 ndarray도 type을 바꿀 수 있다.
arr1 = arr.astype(np.float64)
print(arr.dtype,   arr1.dtype)

1 int32 (3,)
int32 float64


In [3]:
    
#2차원 ndarray 생성
arr= np.array([[1,2,3],[4,5,6]])
arr.shape



(2, 3)

In [4]:
# 기본 methods
# zeros, ones, arange ( arange는 python의 range객체와 같이 사용)
a = np.zeros((2,3))
b = np.ones((1,5))
c = np.arange(1,6,2)
d = np.zeros_like(c) # 인자로 받은 array와 동일한 shape과 dtype의 zeros 배열 생성
print(a,b,c,d,sep= '\n')

# np.linspace(a,b,num) a<= 원소 <=b 인 원소 num개를 균등한 간격으로 가진 배열 생성
a = np.linspace(0,1,10)
print(a)

# np.random.random((shape)) -> 0~1사이의 균등분포에서 원소를 추출하여 shape를 가진 배열 생성, shape은 tuple형태로 전달
a = np.random.random((2,4))
print(a)

#np.random.randn(shape) mean = 0, std = 1인 정규분포에서 shape size의 난수를 원소로하는 배열을 생성, shape는 ()없이 전달 randn이랑 reshape,transpose만 shape를 ()에 싸지 않고 전달
a = np.random.randn(2,4)
print(a)

# np.random.normal(loc,scale,(shape))의 경우 평균과 표준편차를 지정할 수 있음

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]]
[1 3 5]
[0 0 0]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.82107069 0.84098435 0.22987558 0.89058128]
 [0.23349367 0.63858602 0.01340648 0.67508069]]
[[ 1.15782251 -2.02961804  2.65473651  0.64790571]
 [-0.39935221  1.16295594  0.24673823 -1.33904791]]


In [5]:
''' 배열간 또는 스칼라와 element wise 연산'''
na = np.array([1,2,3])
nb = np.array([4,5,6])
print(na + nb, na * nb, na *2, sep = ' ')



[5 7 9] [ 4 10 18] [2 4 6]


In [6]:
''' numpy indexing & slicing
numpy의 1차원배열의 경우 파이썬 내장 리스트의 indexing과 slicing을 동일하게 적용할 수 있다. 
다만 slicing을 할 때, shallow copy이므로 deep copy 객체를 생성하려면.copy()함수를 사용한다.
다차원 배열의 경우에는 python 내장 리스트와 같이 indexing과 slicing을 할 수 잇으나comma를 통해서 indexing과 slicing을 할 수 있다.'''

aa = np.array([1,2,3,4,5])
print(aa[0],aa[:3],end='\n\n')

bb = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(bb[1,0],bb[:2,:2],bb[1,:],bb[:,0],bb[:,:2],sep ='\n')

1 [1 2 3]

6
[[1 2]
 [6 7]]
[ 6  7  8  9 10]
[1 6]
[[1 2]
 [6 7]]


In [7]:
# 논리 인덱싱
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.random.seed(0)

data = np.random.randn(7, 4)
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [8]:
arr = data[names == "Bob",:2]
print(arr, end = '\n\n') #이 때 arr는 deep copy 객체
mask = (names == 'Bob') | (names == 'Will') # numpy 논리 연산자로 and or등을 사용할 수 없고 반드시 &,|를 사용해야된다.
arr_m = data[mask]
# 논리 인덱싱으로 원본 데이터 수정
data[data < 0] = 0
print(data)

[[1.76405235 0.40015721]
 [0.76103773 0.12167502]]

[[1.76405235 0.40015721 0.97873798 2.2408932 ]
 [1.86755799 0.         0.95008842 0.        ]
 [0.         0.4105985  0.14404357 1.45427351]
 [0.76103773 0.12167502 0.44386323 0.33367433]
 [1.49407907 0.         0.3130677  0.        ]
 [0.         0.6536186  0.8644362  0.        ]
 [2.26975462 0.         0.04575852 0.        ]]


In [9]:
# 정수 인덱싱
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i
print(arr, end ='\n\n')
# 음수를 포함한 행 인덱스 배열을 ndarray의 index로 주어 특정 행만 뽑을 수 있다.
print(arr[[-4, -5, 0, 6]], '\n\n')
#  2개의 인덱스 배열을 인자로 주면 인덱스 배열들의 대응하는 원소별 튜플에 해당하는 원소들로 구성된 1차원 ndarray가 반환된다.  
print(arr[[-4, -5, 0, 6],[0,2,3,1]])


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]] 


[4. 3. 0. 6.]


In [10]:
# 행렬의 전치
arr = np.arange(0,20).reshape(4,5)
arr = arr.dot(arr.T) # dot연산등에 활용
print(arr,end = '\n\n')

arr_3 = np.arange(2*3*4).reshape(2,3,4) # reshape 에 인자로 -1을 넣으면 예시의 2*3*4의 값을 맞추는 인자가 -1대신 채워진다. ex) 2,3,-1 -> -1대신 4가 채워짐
print(arr_3)

arr_3 = arr_3.transpose(2,0,1) # axis 0 -> 면, 1 -> 행, 2-> 열 ->> 2 * 3 * 4 행렬을 4*2*3 행렬로 전치 
# 같은 열 기준으로 4개의 면이 구성 각 면별로 2행( 기존의 면으로 구분되던 원소들이 행으로), 3열 (기존의 행을 구성하던 원소들이 열로) 로 전환된다.
# 비슷한 함수 arr.swapaxes(0,2) -> 면과 열의 축 전치 ==> arr.transpose(2,1,0)

[[  30   80  130  180]
 [  80  255  430  605]
 [ 130  430  730 1030]
 [ 180  605 1030 1455]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
''' 배열의 병합과 분리'''
# axis defautl -> 0, concatenate할 배열들을 튜플로 전달
a = np.array([[1,2,3],[10,20,30]])
b = np.array([[4,5,6],[40,50,60]])
c = np.concatenate((a,b),axis = 1)
print(c,end='\n\n')
a = np.array([1,2,34])
b = np.array([2,5,4])
c = np.concatenate((a,b))
print(c,end='\n\n')

# split(array, [index], axis = 0) axis -> default 0
# 분리된 배열은 튜플로 전달받음
a = np.array([[1,2,3],[4,5,6]])

c,d = np.split(a,[1],axis=1)   
print(c,d,sep ='\n')


[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]]

[ 1  2 34  2  5  4]

[[1]
 [4]]
[[2 3]
 [5 6]]


In [12]:
# 범용 함수 ndarray 성분별 연산을 한 ndarray를 return한다.
print(np.sqrt(a)) #-> square root (제곱근)
print(np.exp(a)) # -> 성분별 지수표현
print(np.maximum(a,b)) # 두 배열의 성분별 가장 큰 성분 ndarray return
# 범용함수는 out 이라는 인자에 원본이 수정되길 원하는 ndarray를 주어 원본을 수정할 수 있다.
# 이 외에 sign, mod등의 함수등이 있다.

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[2 5 4]
 [4 5 6]]


In [13]:
# meshgrid
# x_scale (x좌표 범위) 1차원배열, y_scale (y좌표 범위) 1차원 배열을 전달받아
# 2차원 격자점을 구성하는 x범위 * y범위의 2차원 배열(x범위의 원소 하나당 y범위 원소 개수 만큼의 원소가 필요) 과, y범위 * x범위의 2차원 배열을 튜플로 return한다.
arr1 = np.linspace(1,10,10)
arr2 = np.linspace(-10,-1,10)
x,y = np.meshgrid(arr1,arr2)
print(x,y,sep ='\n')
# 삼항 연산
arr = np.random.randn(10)
np.where(arr>0,1,0) # 인자별로 condition, true expression, false expression이다

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [ -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.]
 [ -8.  -8.  -8.  -8.  -8.  -8.  -8.  -8.  -8.  -8.]
 [ -7.  -7.  -7.  -7.  -7.  -7.  -7.  -7.  -7.  -7.]
 [ -6.  -6.  -6.  -6.  -6.  -6.  -6.  -6.  -6.  -6.]
 [ -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.]
 [ -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.]
 [ -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.]
 [ -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.]
 [ -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.]]


array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [14]:
#수학 통계 논리 정렬 method
arr = np.random.normal(10,1,(5,4))
print(arr,end='\n\n')
print(f"평균:{arr.mean()},표준편차:{arr.std()},분산:{arr.var()},합:{arr.sum()},최댓값:{arr.max()},최솟값:{arr.min()}",end='\n\n')
print(arr.cumsum(),arr.cumprod(),sep='\n',end='\n\n') #각각 누적합이 표현된 배열과 누적곱이 표현된 배열 return
# 이외에도 argmax,argmin함수 -> index별 최대,최소 return
#논리 연산 활용
arr = np.array([ True,  True,  True,  True,  True, False, False,  True, False,
        True])
print((arr>0).sum(),any(arr>0),all(arr>0),end='\n\n')
#정렬 method
arr = np.random.randn(2,3)
print(arr,end='\n\n')
arr.sort()
print(arr) #axis = default(0)이어서 행별로 정렬된 모습

[[ 9.61267318  9.69769725  8.95144703  8.57998206]
 [ 8.29372981 11.9507754   9.49034782  9.5619257 ]
 [ 8.74720464 10.77749036  8.38610215  9.78725972]
 [ 9.10453344 10.3869025   9.48919486  8.81936782]
 [ 9.97181777 10.42833187 10.06651722 10.3024719 ]]

평균:9.620288624815684,표준편차:0.8761478836329045,분산:0.7676351139944175,합:192.4057724963137,최댓값:11.95077539523179,최솟값:8.293729809374987

[  9.61267318  19.31037043  28.26181747  36.84179953  45.13552934
  57.08630473  66.57665255  76.13857825  84.88578289  95.66327325
 104.0493754  113.83663512 122.94116856 133.32807106 142.81726592
 151.63663373 161.60845151 172.03678338 182.1033006  192.4057725 ]
[9.61267318e+00 9.32207943e+01 8.34461003e+02 7.15966043e+03
 5.93802892e+04 7.09640499e+05 6.73473516e+06 6.43970372e+07
 5.63294063e+08 6.07089633e+09 5.09111567e+10 4.98280714e+11
 4.53661342e+12 4.71213613e+13 4.47143779e+14 3.94352546e+15
 3.93241172e+16 4.10084945e+17 4.12812716e+18 4.25299141e+19]

7 True False

[[-0.63432209 -0.36274117

In [18]:
# 선형대수 함수
# 행렬곱 연산 dot 함수 (python 3.5 이상 부터는 @라는 연산자로 dot 대체가능 ex)a @ b)
a = np.random.randn(3,4)
b= np.random.randn(4,3)
print(a.dot(b),np.dot(a,b),sep='\n',end='\n\n')

# numpy.linalg -> 역행렬, 행렬식, 분해 함수 등 포함

from numpy.linalg import inv, det

X = np.random.randn(3, 3)
print(det(X),end='\n\n') # 행렬식 return
print(inv(X),end='\n\n') # 역행렬 return


[[ 1.71361706 -1.39846694  1.44384403]
 [-0.2764774  -0.23821622 -1.096304  ]
 [-3.18230161  2.8214342   1.39753731]]
[[ 1.71361706 -1.39846694  1.44384403]
 [-0.2764774  -0.23821622 -1.096304  ]
 [-3.18230161  2.8214342   1.39753731]]

-0.5407583180361959

[[ 3.56730319 -0.38978817 -0.17305708]
 [-0.18910906  0.3522893  -0.50529179]
 [-0.77080427 -0.77348985 -0.19517602]]



In [16]:
#numpy.random
np.random.seed(0)
# 난수 생성 -> 이후 항상 같은 난수 사용
#np.random.RandomState(123) 국소적 난수 생성

# shuffle과 permutation
# shuffle은 원본 배열의 순서를 변경, permutation은 수정된 객체 반환
arr = np.linspace(1,10,10)
print(np.random.permutation(arr))
np.random.shuffle(arr)
print(arr)

# rand와 randint
print(np.random.rand(3,2),np.random.randint(5),sep='\n') # rand는 0~1의 uniform dist에서 인자 사이즈의 배열 return, randint는 0~4의 uniform 정수 dist에서 정수 한개 return
# binomial, gamma,uniform
print(np.random.binomial(n=1,p=0.5,size=10)) #n->trial, p->probability

[ 3.  9.  5. 10.  2.  7.  8.  4.  1.  6.]
[ 4.  6.  2.  3. 10.  9.  1.  7.  8.  5.]
[[0.81216873 0.47997717]
 [0.3927848  0.83607876]
 [0.33739616 0.64817187]]
0
[1 1 1 1 1 0 1 0 1 0]


In [17]:
# # numpy array file
# arr = np.arange(10)
# # np.save('./f1',arr) #경로에 배열을 바이너리 파일로 저장 .npy확장자
# # arr1 = np.load('./f1.npy') #load
# # # 여러 배열 저장
# # np.savez('./f2',a =arr, b = arr1) #a와 b라는 key지정 가능, npz라는 확장자
# # arr2 = np.load('./f2.npz')
# arr['a'] # key로 호출